apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  namespace: al-nafi
  labels:
    app: myapp
spec:
  containers:
    - name: nginx
      image: nginx:stable
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "1.5Gi"
