apiVersion: v1
kind: Pod
metadata:
   name: test-pod-4
spec:
 securityContext: # Definie security on POD Level 
         runAsUser: 1003
   
 containers:
   - name: ubuntu-container-4
     image: ubuntu
     command: [ "sleep" ,"5000" ]
     securityContext: # Definie security on container Level 
         runAsUser: 1007


   - name: ubuntu-sidecar
     image: ubuntu
     command: ["sleep", "4000"]
