apiVersion: v1
kind: Pod
metadata:
   name: test-pod-3
spec:
 securityContext: # Definie security on POD Level 
         runAsUser: 1000
   
 containers:
   - name: ubuntu-container-3
     image: ubuntu
     command: [ "sleep" ,"5000" ]
     securityContext: # Definie security on container Level 
         runAsUser: 1008
