apiVersion: v1
kind: Pod
metadata:
   name: test-pod-2
spec:
 containers:
   - name: ubuntu-container-2
     image: ubuntu
     command: [ "sleep" ,"5000" ]
     securityContext: 
         runAsUser: 1002
