apiVersion: v1
kind: Service
metadata:
  name: dashboard-svc  # <- Add this line
  labels:
    app: dashboard
    name: dashboard-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dashboard
  type: NodePort
