apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
 replicas: 1
 selector:
    matchLabels:
            app: bluegreen-deployment
            color: blue
 template:
   metadata:
     labels:
       app: bluegreen-deployment
       color: blue

   spec:
     containers:
        - name: nginx
          image: linuxacademycontent/ckad-nginx:blue
          ports:
             - containerPort: 80 

