apiVersion: v1
kind: Pod
metadata:
     name: init-cont-pod
spec:
   containers:
   - name: main-cont
     image: nginx:stable
   initContainers:
   - name: init-cont
     image: busybox:stable
     command: ['sh', '-c', 'sleep 60']
            
