apiVersion: apps/v1
kind: Deployment
metadata:
     name: myapp-deployment
     labels:
        app: myapp
        tier: frontend
spec:
 replicas: 3
 selector:
    matchLabels: 
         app: al-nafi-app
 template:
     metadata: 
        name: nginx-2
        labels:
          app: al-nafi-app
     spec:
       containers:
        - name: nginx-container
          image: nginx:stable
      
