apiVersion: apps/v1
kind: Deployment
metadata:
     name: simple-deployment
     labels:
        app: nginx
spec:
 replicas: 3
 selector:
    matchLabels: 
         app: frontend
 template:
     metadata: 
        labels:
          app: frontend
     spec:
       containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80 
