apiVersion: v1
kind: Pod
metadata:
  name: memory-stress-pod
spec:
  containers:
  - name: memory-stress
    image: polinux/stress
    command:
    - stress
    args:
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "15M"
    - "--vm-hang"
    - "1"
    resources:
      limits:
        memory: "100Mi"
      requests:
        memory: "50Mi"
