apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: work-pod-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: test
  type: NodePort
status:
  loadBalancer: {}
