apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  namespace: default
spec:
  backoffLimit: 9
  activeDeadlineSeconds: 40
  completions: 5
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: example-jobs
          image: busybox
          command: ["echo", "This is test job !"]

