apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: the-pod
  name: the-pod
spec:
  containers:
  - image: busybox:stable
    name: the-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
