apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: al-nafi-nginx-pod
  name: redis-service
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: al-nafi-nginx-pod
status:
  loadBalancer: {}
