apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    tier: backend
    bu: finance
  name: test-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        env: prod
        
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
