apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: default
  labels:
    name: webapp-pod
spec:
 containers:
   - name: webapp
     image: kodekloud/simple-webapp-mysql
     envFrom:
      - secretRef:
           name: db-secret 
