apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
  labels:
    name: webapp-service
spec:
  ports:
   - nodePort: 30080
     port: 80
     protocol: TCP
     targetPort: 8080 
  selector:
     name: webapp-pod
  type: NodePort
